### PR TITLE
out_mongo: Support dynamic database name by built-in placeholders

### PR DESCRIPTION
**Pull request by cosmo0920**
Fixes https://github.com/fluent/fluent-plugin-mongo/issues/85.

For collection, it is already supported.
Signed-off-by: Hiroshi Hatake <hatake@clear-code.com>

### CODE REVIEW

**Comment by repeatedly** [comment]
Could you update README for database with placeholder?

**Comment by cosmo0920** [comment]
I added a new placeholder note in README.
Should I rewrite database and collection parameter usage with built-in placeholders instead?

**Comment by repeatedly** [comment]
> Should I rewrite database and collection parameter usage with built-in placeholders instead?

I think no need for now.

**Comment by repeatedly** [comment]
Thanks!

**Pull request merged**
