### PR TITLE
Revise mongod lifecycle

### PR DESCRIPTION
**Pull request by soutaro**
I tried to write tests for `MongoTailInput`, and found some difficulties.

* I don't want `killall mongod` because it also kills my mongod I'm using for my app development
* The mongod start/stop management looks broken; it does not kill mongod as expected

I did refactor mongod lifecycle management in tests.

* Extract test cases into module from `MongoOutputTest` and `MongoReplOutputTest`
* Use `TestCase.startup` and `TestCase.shutdown` to start and stop mongod
* Use `Process.kill` to stop mongod

### CODE REVIEW

**Comment by soutaro** [comment]
CI stil fails due to `bundle install` failure...

**Comment by repeatedly** [comment]
Sorry for the delay. Could you rebase the commit to rerun test on Travis-CI?

**Comment by soutaro** [comment]
I'm sorry for late response. I did rebase, and now it's green!

**Comment by repeatedly** [comment]
Thanks!

**Comment by soutaro** [comment]
:fireworks:

**Pull request merged**
